### ISSUE TITLE
Sub-line higlights for changes

### ISSUE THREAD

**Issue by jzaefferer** [scottgonzalez/pretty-diff#16]
I'm not sure how to call this, maybe its actually what the word-diff issue is about. Anyway, I'd like to have a diff like this from pretty-diff: https://github.com/jquery/infrastructure/commit/ab9a2c03d683e8d409800ee0f5a65b6d3373411b

The extra highlights within each line makes it much easier to spot the actual changes.

**Comment by scottgonzalez** [comment]
That's word diff. See #12.
