### ISSUE TITLE
Show "not a git repository" when run on non git folders

### ISSUE THREAD

**Issue by thewhitetulip** [scottgonzalez/pretty-diff#18]
I ran pretty-diff in an incorrect folder, which wasn't a git repo, and I got an error saying `invalid data`, whilst it is totally okay to show this error, it would have been nicer to say `invalid git repo`.

**Comment by scottgonzalez** [comment]
Good point. I'll try to get to this tonight.

**Comment by thewhitetulip** [comment]
:+1:

**Comment by scottgonzalez** [comment]
Published in v0.3.1.
