### ISSUE TITLE
Got an Error: Problems parsing JSON error when doing gist-diff

### ISSUE THREAD

**Issue by alkaithil** [scottgonzalez/pretty-diff#26]
I did

`gist-diff HEAD^`

and was prompted for my password, as expected. But after entering it I got
`[Error: Problems parsing JSON]`

Any ideas?

**Comment by scottgonzalez** [comment]
Hmm...I wonder if there's something in the diff itself. Are you able to post the raw diff output?

**Comment by alkaithil** [comment]
Do you mean the output of doing a `git diff HEAD^` ? I'ts a bit long, I pasted it in a gist: https://gist.github.com/alkaithil/e3d50777b7f2065a2b88

**Comment by scottgonzalez** [comment]
Thanks, that allowed me to reproduce the problem. I'll have a fix soon.

**Comment by scottgonzalez** [comment]
Released v0.6.0.
