### ISSUE TITLE
Does not work upon comparing files that are not versioned (non git folders)

### ISSUE THREAD

**Issue by daformat** [scottgonzalez/pretty-diff#28]
So, git diff works pretty much without any trouble when you pass it local files that are from in non git versioned folders. Trying to get the same result with pretty-diff is a total fail.

Here is the git diff commands I'm using on a non git folder (working and giving the same result, which is expected)

```
git diff --word-diff file1.html file2.html
git diff --color-words --word-diff file1.html file2.html
git diff --no-index --color-words --word-diff file1.html file2.html
git diff --no-index --color-words --word-diff -- file1.html file2.html
```

All of these commands perfectly produces a colored word-diff, and works on non git initialized folders:
![image](https://cloud.githubusercontent.com/assets/1694893/21494118/9aa5ba0a-cc0f-11e6-9e77-9c7222e1ec4b.png)

I get absolutely no result when trying the same thing with pretty-diff. Is there any configuration option I'm missing somewhere? I thought pretty-diff just "carried out" the args to git diff and expected to work out-of-the-box from what the README states "Simply use pretty-diff the same way you use git diff". Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/1694893/21494093/6199c922-cc0f-11e6-922e-fe6e985fbce3.png)

I also tried inserting "diff" between pretty-diff and the rest of the args but it returns "error: not a git repository".

**Comment by scottgonzalez** [comment]
I didn't know that `git diff` worked outside of git repositories, but I guess that makes sense. The problem was that `git diff` exits with a code of `1` when you do that, even though it renders the diff. Since the exit code indicates an error, `pretty-diff` just prints out `stderr` from `git diff`, but in this case `stderr` is empty.

I've updated `pretty-diff` to handle this odd case and release v0.6.1.

**Comment by daformat** [comment]
Yeah, I just got the notification and saw the 'hack' you had to pull of your hat :) Thanks for fixing this so quickly!
